### ISSUE TITLE
Adding support for atime and mtime

### ISSUE THREAD

**Issue by zeroos** [Changaco/python-libarchive-c#48]
Hey guys,

I have tried to add ctime and atime field support to the library. Here you may take a look at my efforts: https://github.com/zeroos/python-libarchive-c/tree/atime-and-ctime

Often the solution seems to work, but, among others, the `test_convert` test fails. I have tried to understand the issue here and it seems that the `memory_writer(buf2, 'zip')` call is loosing the information about the created/modified date. It looks a little bit as an upstream issue. Could you please confirm that and maybe provide some broader image, why those fields were skipped in the first place?

Best wishes,
Michał

**Comment by Changaco** [comment]
Hi,

The problem seems to be related to the archive format used. If you use `zip` the `atime` and `ctime` are okay, but they're not with `tar` archives for example.

I recommend writing a specific test for `atime` and `ctime` instead of checking them in the `check_archive()` function which is used by many tests.

**Comment by zeroos** [comment]
Hey,

thanks for this suggestion! I did not realise the ctime and atime are handled so differently than mtime. I have created a pull request here for this feature: https://github.com/Changaco/python-libarchive-c/pull/49 , I hope you'd find it helpful.
